name: GitHub CI

on:
  push:
    branches:
      - 'jest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 18.x
        uses: actions/setup-node@master
        with:
          node-version: 18

      - name: Install
        run: npm ci

      - name: Unit test
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
